services:
  quickwit:
    image: quickwit/quickwit:v0.9.0-rc
    command: run
    ports:
      - "7290:7280"  # REST API / UI
      - "7291:7281"  # OTLP gRPC
    volumes:
      - quickwit-data:/quickwit/qwdata

volumes:
  quickwit-data:
