{
  description = "Opinionated observability UI built on Quickwit";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    zig2nix.url = "github:Cloudef/zig2nix";
  };

  outputs = {
    self,
    nixpkgs,
    zig2nix,
  }: let
    flake-utils = zig2nix.inputs.flake-utils;
  in
    flake-utils.lib.eachDefaultSystem (
      system: let
        env = zig2nix.outputs.zig-env.${system} {
          inherit nixpkgs;
        };

        pkgs = env.pkgs;
        pnpmDeps = pkgs.fetchPnpmDeps {
          pname = "winnow-frontend";
          src = ./frontend;
          hash = "sha256-AXMvjQF4tBjhagIUFFfPSNWjN01WAJ2pIAI77r7vCCc=";
          fetcherVersion = 4;
        };

        # Zig dependencies, built from build.zig.zon2json-lock.
        #
        # zig2nix's own dependency fetcher (generated by zon2nix) is broken with
        # zig 0.16: `zig fetch` fails to unpack zip archives ("failed to create
        # temporary zip file: FileNotFound") unless a tmp/ dir already exists in
        # the cache dir it's given. zig-protobuf v5 ships its protoc binaries as
        # lazy zip dependencies, which trips this. Until zig2nix (or zig) fixes
        # it, we replicate the generated fetcher here with the missing mkdir.
        fetchZigDep = {
          name,
          url,
          hash,
        }:
          pkgs.runCommand "${name}.tar.gz" {
            src = url;
            nativeBuildInputs = [env.zig];
            outputHash = hash;
            outputHashMode = "flat";
          } ''
            mkdir -p "$TMPDIR/tmp" # zig 0.16 zip unpacking needs this to exist
            touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
            hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
            mv "$TMPDIR/p/$hash.tar.gz" "$out"
          '';
        zigDeps = pkgs.linkFarm "winnow-dependencies" (pkgs.lib.mapAttrsToList (zhash: dep: {
            name = "${zhash}.tar.gz";
            path = fetchZigDep {inherit (dep) name url hash;};
          })
          (builtins.fromJSON (builtins.readFile ./backend/build.zig.zon2json-lock)));

        # nixpkgs still ships libjwt 1.x; the sample module needs the 3.x API.
        libjwt3 = pkgs.stdenv.mkDerivation (finalAttrs: {
          pname = "libjwt";
          version = "3.6.1";

          src = pkgs.fetchFromGitHub {
            owner = "benmcollins";
            repo = "libjwt";
            rev = "v${finalAttrs.version}";
            hash = "sha256-XPo26nmz+0/rMi9wwC1lC2VdWgKRgIqf/6PbevvAuW8=";
          };

          nativeBuildInputs = [pkgs.cmake pkgs.pkg-config];
          buildInputs = [pkgs.jansson pkgs.openssl pkgs.curl];

          cmakeFlags = [
            "-DWITH_GNUTLS=OFF" # auto-detected otherwise; keep the closure deterministic
            "-DWITH_LIBCURL=ON" # jwks_load_fromurl* used by the sample module
            "-DWITH_TESTS=OFF"
          ];

          meta = {
            description = "JWT C Library";
            homepage = "https://github.com/benmcollins/libjwt";
            license = pkgs.lib.licenses.mpl20;
          };
        });
      in {
        # Exposed so the dependency fetcher workaround can be tested standalone:
        # `nix build .#zig-deps`
        packages.zig-deps = zigDeps;

        packages.libjwt = libjwt3;

        packages.frontend = pkgs.stdenvNoCC.mkDerivation {
          pname = "winnow-frontend";
          version = "0.0.0";
          src = ./frontend;
          nativeBuildInputs = [
            pkgs.nodejs_24
            pkgs.pnpm
            pkgs.pnpmConfigHook
          ];
          inherit pnpmDeps;
          buildPhase = ''
            pnpm build
          '';
          installPhase = ''
            cp -r dist $out
          '';
        };

        packages.default =
          (env.package {
            pname = "winnow";
            version = "0.0.0";
            src = ./backend;

            # protoc is needed for the gen-proto build step
            nativeBuildInputs = [pkgs.protobuf];

            # Generate protobuf Zig code and embed frontend assets before the main build.
            # This creates static_assets.zig so zig build's auto-detect skips frontend steps.
            preBuild = ''
              # Link frontend dist for @embedFile resolution
              ln -s ${self.packages.${system}.frontend} src/server/frontend-dist

              # Generate static asset embedding module
              bash ${./scripts/embed-frontend.sh} src/server/frontend-dist src/server/static_assets.zig

              # Generate protobuf code. No --system flag: with zig 0.16 the
              # dependency link farm holds <hash>.tar.gz files, which the
              # package cache accepts but --system mode does not.
              zig build gen-proto
            '';

            doCheck = true;
            checkPhase = ''
              zig build test
            '';

            meta.mainProgram = "winnow";
          }).overrideAttrs (old: {
            # Swap zig2nix's broken dependency derivation for our fixed one
            # (see fetchZigDep above). Both attrs reference the old one, so both
            # must be replaced or nix still tries to build it.
            postConfigure = ''
              ln -s ${zigDeps} "$ZIG_GLOBAL_CACHE_DIR"/p
            '';
            disallowedReferences = [env.zig env.zig.hook pkgs.removeReferencesTo zigDeps];
          });

        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            # Backend
            zig
            zls

            # Frontend
            nodejs_24
            pnpm

            # Tools
            protobuf
            grpcurl
            curl
            jq

            # Sample module dependencies
            libjwt3
            pkg-config

            # Auth testing rig (dummy JWKS endpoint + token signer)
            self.packages.${system}.jwks-server
            self.packages.${system}.generate-token

            # Data generation
            self.packages.${system}.generate-data
            self.packages.${system}.nuke-indices
          ];

          shellHook = ''
            export QUICKWIT_URL=http://localhost:7290
            export WINNOW_AUTH_JWKS_URL=http://localhost:7292/jwks.json
            echo "winnow dev shell"
            echo "  zig:  $(zig version)"
            echo "  node: $(node --version)"
            echo "  pnpm: $(pnpm --version)"
          '';
        };

        checks = pkgs.lib.optionalAttrs pkgs.stdenv.isLinux {
          integration = pkgs.callPackage ./tests/integration.nix {
            winnow = self.packages.${system}.default;
          };
        };

        packages.generate-data = pkgs.writers.writePython3Bin "generate-data" {
          libraries = [
            pkgs.python3Packages.opentelemetry-api
            pkgs.python3Packages.opentelemetry-sdk
            pkgs.python3Packages.opentelemetry-exporter-otlp-proto-http
          ];
          doCheck = false;
        } (builtins.readFile ./scripts/generate-data.py);

        # Auth testing rig: jwks-server serves a dummy JWKS (generating a dev
        # RSA keypair on first run); generate-token signs JWTs with the same
        # key. They share the keys dir (default ./.dev-jwks, override with
        # WINNOW_DEV_JWKS_DIR or --keys-dir).
        packages.jwks-server = pkgs.writers.writePython3Bin "jwks-server" {
          libraries = with pkgs.python3Packages; [pyjwt cryptography];
        } (builtins.readFile ./scripts/jwks-server.py);

        packages.generate-token = pkgs.writers.writePython3Bin "generate-token" {
          libraries = with pkgs.python3Packages; [pyjwt cryptography];
        } (builtins.readFile ./scripts/generate-token.py);

        packages.nuke-indices = pkgs.writeShellScriptBin "nuke-indices" ''
          exec ${pkgs.python3}/bin/python3 ${./scripts/nuke-indices.py} "$@"
        '';

        # TODO: packages.docker-image = OCI image
      }
    );
}
